# All generated files go into the BUILD directory
BUILD		 = build

# Apache module name
MODNAME		 = dtprovider

# DTrace provider name
PROVIDER	 = http

# Compile flags
CC		 = gcc
CFLAGS		+= -Wall
AP_CPPFLAGS	:= $(shell apxs -q CPPFLAGS) -I$(shell apxs -q INCLUDEDIR)
SOLDFLAGS	 = -shared -fPIC

# Source layout
CSRCS		 = src/$(MODNAME).c
SOFILE		 = $(BUILD)/mod_$(MODNAME).so
OBJFILES	 = $(CSRCS:src/%.c=$(BUILD)/%.o)
EXTRAOBJFILES	 = $(BUILD)/$(PROVIDER)_provider.o

all: $(SOFILE)

clean:
	-rm -rf $(BUILD)

$(BUILD):
	mkdir -p $(BUILD)

#
# The shared object combines the object files generated from C sources with the
# one generated by DTrace.  XXX We use ld directly here rather than gcc because
# the Apache build process leaves the shared object with unreferenced symbols,
# which gcc doesn't like.  Admittedly this is kind of weird, but it works
# because Apache will dlopen() the shared object from a context where these
# symbols are defined.  ld allows this by defalt for shared libraries, but
# there should be some way to convince gcc that it's okay.  Note that ld emits
# warnings here because it doesn't like being invoked outside a compiler
# driver.
#
$(SOFILE): $(OBJFILES) $(EXTRAOBJFILES)
	$(LD) $(SOLDFLAGS) $(LDFLAGS) -o $@ $^

#
# Object files are generated either by building the corresponding source file
# or by running "dtrace -G" on the provider file using the other object files.
#
$(BUILD)/%.o: src/%.c | $(BUILD)
	$(CC) $(CFLAGS) $(CPPFLAGS) $(AP_CPPFLAGS) -c -o $@ $<

$(BUILD)/$(PROVIDER)_provider.o: src/$(PROVIDER)_provider.d $(OBJFILES) | $(BUILD)
	dtrace -xnolibs -G -o $@ -s $< $(OBJFILES)

#
# The provider header file is generated directly by "dtrace -h".
#
$(BUILD)/$(PROVIDER)_provider.h: src/$(PROVIDER)_provider.d | $(BUILD)
	dtrace -xnolibs -h -o $@ -s $<
